name: skeletons
description: A Flutter package for building custom skeleton widgets to mimic the page's layout while loading.
version: 0.0.3
homepage: https://github.com/badjio/skeletons/

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

# The following section is specific to Flutter.
flutter:
